Add support for EVW3200-Wifi + CLI tool
mzdrale/pyubee pull request #3
Opened 2019-03-09 11:07 UTC by StevenLooman

I noticed this library via the Home Assistant integration. Great work!

The library, as advertised, has been written for and tested with `Ubee EVW32C-0N`. Unfortunately, this does not work for my `Ubee EVW3200-Wifi` router/cable modem. This pull request adds support for this device.

Please do not merge yet, but do test it on your own router. This works for me, but I might have broken something for your model.

2019-03-11 13:48 UTC, mzdrale commented
Thanks @StevenLooman, great work!
I just installed your version. I will give it a try and I will let you know if there is need to change something. So far looks good.

2019-03-11 13:52 UTC, mzdrale requested changes
So far looks good. There is only one typo in code and README.

2019-03-11 13:52 UTC, mzdrale commented on README.md
> +  password       Username
This is typo, should be `password    Password`. ;)

2019-03-11 13:52 UTC, mzdrale commented on pyubee/__main__.py
> +    parser.add_argument('password', help='Username')
Typo. Should be:

`parser.add_argument('password', help='Password')`

2019-03-11 19:23 UTC, StevenLooman commented
Thank you for the review, fixed!

I think you've checked the columns names as well. I'm removing the question marks.

2019-03-12 09:45 UTC, mzdrale approved these changes

2019-03-12 09:46 UTC, merged

2019-03-12 13:55 UTC, mzdrale commented
Thank you @StevenLooman!
I've merged your changes and released version 0.3 ([GitHub](https://github.com/mzdrale/pyubee/releases), [PyPi](https://pypi.org/project/pyubee/)).

I've also made some changes to [Home Assistant Ubee Device Tracker](https://www.home-assistant.io/components/device_tracker.ubee), but I want to test it more before I create Home Assistant PR.

2019-03-12 16:09 UTC, StevenLooman commented
Great! Can I help with testing?

2019-03-13 13:58 UTC, mzdrale commented
Sure, it would be great. I've sent email to you with instructions.